name: Build

on:
  push:
    paths-ignore:
      - LICENSE
      - README.md

  pull_request:
    paths-ignore:
      - LICENSE
      - README.md

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        include:
          - os: ubuntu-20.04
    steps:     
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y clang g++-multilib libmysqlclient-dev
          
      - name: Setup Python for AMBuild (Linux)
        if: runner.os == 'Linux'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Select clang compiler (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          clang --version
          clang++ --version

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: mysql_mm
          submodules: recursive

      - name: Checkout AMBuild
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/ambuild
          path: ambuild

      - name: Install AMBuild
        run: |
          cd ambuild && python setup.py install && cd ..

      - name: Build
        working-directory: mysql_mm
        shell: bash
        run: |
          mkdir build && cd build
          python ../configure.py --enable-optimize --symbol-files --sdks cs2
          ambuild

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mysql_mm-${{ runner.os }}-${{ github.run_number }}
          path: mysql_mm/build/package
          local_dir: mysql_mm/build/package
          server_dir: /build/${{ github.run_number }}/
          secure: false
